### PR TITLE
Fix classic form boolean logic

### LINKED ISSUE #1212: Classic form: enable "simple logic" options
What ADS classic calls "simple logic" is the use of "+" and "-" to require or exclude a particular word in the result list.  If I now use this on a search in the author field such as `+kurtz, m; -accomazzi, a` (on separate lines) the form creates the query `author:("+kurtz, m" "-accomazzi, a")` in which the "+" and "-" signs are ignored by the search engine.  The query should instead by `author:(+"kurtz, m" -"accomazzi, a")`

### PR DESCRIPTION
**Pull request by thostetler**
fixes #1212

### CODE REVIEW

File: src/js/widgets/classic_form/widget.js [hunk 1]
```diff
@@ -123,9 +123,41 @@ define([
...
+
+              // test the first character for presence of (+ or -)
+              if (/[+\-]/.test(line[0])) {
+
+                // +blah -> +"blah"
+                line = line[0] + '"' + line.slice(1) + '" ';
+              } else {
+
+                // blah -> +"blah"
+                line = '+"' + line + '" ';
```
Comment (romanchyla) [inline src/js/widgets/classic_form/widget.js]: please use the following:

```updater.quoteIfNecessary(line)```

https://github.com/adsabs/bumblebee/blob/0b242c9ecaf1e831c5673faf0f72b72b0ed6957b/src/js/components/api_query_updater.js#L270

the quotes do change how the search engine handles stuff (in some situations); so better to play safe and not use quotes if we don't have to

**Comment by thostetler** [comment]
Updated the PR.
